name: test3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pytorch=1.3.1
  - transformers=2.1.1
  - scipy=1.3.2
  - numpy=1.17.4
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - scikit-learn=0.22.1
  - pip
  - pip:
    - sentencepiece==0.1.85
